# Verifies that the build process succeeds, there aren't any lint errors and tests pass
name: Smoke testing CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs: 
  Smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint
      
      - name: Test
        run: yarn test
